- hosts: wordpress
  become: true
  tasks:
    - name: Install NGINX, MariaDB, PHP-FPM
      apt:
        name:
          - nginx
          - mariadb-server
          - php
          - php-fpm
          - php-mysql
        state: present
        update_cache: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/
        remote_src: yes

    - name: Configure NGINX
      template:
        src: wordpress-nginx.conf.j2
        dest: /etc/nginx/sites-available/wordpress
      notify: Reload NGINX

  handlers:
    - name: Reload NGINX
      service:
        name: nginx
        state: restarted
