---
- name: Configure NGINX and PHP-FPM
  hosts: wordpress
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Install PHP and extensions
      apt:
        name:
          - php-fpm
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-zip
        state: present

    - name: Configure PHP
      lineinfile:
        path: /etc/php/8.1/fpm/php.ini
        regexp: '^;?cgi.fix_pathinfo='
        line: 'cgi.fix_pathinfo=0'

    - name: Restart PHP-FPM
      service:
        name: php8.1-fpm
        state: restarted