name: Deploy WordPress Infrastructure

on:
  push:
    branches: [ main ]
    paths: [ 'terraform/**', 'ansible/**' ]
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

jobs:
  terraform:
    name: Terraform Infrastructure Deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    outputs:
      public_ip: ${{ steps.tf_output.outputs.public_ip }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init -reconfigure
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Extract Terraform Output (Public IP)
        id: tf_output
        run: |
          echo "Fetching Terraform output..."
          # Capture only the clean IP value
          PUBLIC_IP=$(terraform output -raw vm_public_ip 2>/dev/null | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
          echo "public_ip=${PUBLIC_IP}" >> $GITHUB_OUTPUT
          echo "Terraform output (clean): ${PUBLIC_IP}"

   
  ansible:
    name: Configure WordPress via Ansible
    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        working-directory: ./ansible

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Ansible & Dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Generate Dynamic Inventory
        run: |
          echo "[wordpress]" > inventory.ini
          echo "${{ needs.terraform.outputs.public_ip }} ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3" >> inventory.ini
          echo "Generated inventory.ini:"
          cat inventory.ini

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini wordpress.yaml

# End of file